import {render, fireEvent, cleanup} from "@solidjs/testing-library";
import {describe, it, expect, afterEach} from "vitest";
import {Colligative} from "./colligative";
afterEach(function (): void {
    cleanup();
});
describe("Colligative route", function (): void {
    it("renders the card with all nine colligative parameter inputs and buttons", function (): void {
        let result = render(function () { return <Colligative />; });
        let soluteMass = result.getByLabelText("Solute mass") as HTMLInputElement;
        let molarMass = result.getByLabelText("Molar mass") as HTMLInputElement;
        let solventMass = result.getByLabelText("Solvent mass") as HTMLInputElement;
        let vanthoff = result.getByLabelText("Van't Hoff factor") as HTMLInputElement;
        let kb = result.getByLabelText("Boiling point constant") as HTMLInputElement;
        let kf = result.getByLabelText("Freezing point constant") as HTMLInputElement;
        let bp = result.getByLabelText("Solvent boiling point") as HTMLInputElement;
        let fp = result.getByLabelText("Solvent freezing point") as HTMLInputElement;
        let p = result.getByLabelText("Solvent vapor pressure") as HTMLInputElement;
        expect(soluteMass).toBeTruthy();
        expect(molarMass).toBeTruthy();
        expect(solventMass).toBeTruthy();
        expect(vanthoff).toBeTruthy();
        expect(kb).toBeTruthy();
        expect(kf).toBeTruthy();
        expect(bp).toBeTruthy();
        expect(fp).toBeTruthy();
        expect(p).toBeTruthy();
        expect(result.getByText("Calculate")).toBeTruthy();
        expect(result.getByText("Clear")).toBeTruthy();
    });
    it("calculates molality for 58.5 g NaCl in 1000 g solvent and displays Molality", async function (): Promise<void> {
        let result = render(function () { return <Colligative />; });
        let soluteMass = result.getByLabelText("Solute mass") as HTMLInputElement;
        soluteMass.value = "58.5";
        fireEvent.input(soluteMass);
        let molarMass = result.getByLabelText("Molar mass") as HTMLInputElement;
        molarMass.value = "58.5";
        fireEvent.input(molarMass);
        let solventMass = result.getByLabelText("Solvent mass") as HTMLInputElement;
        solventMass.value = "1000";
        fireEvent.input(solventMass);
        let vanthoff = result.getByLabelText("Van't Hoff factor") as HTMLInputElement;
        vanthoff.value = "1";
        fireEvent.input(vanthoff);
        let kb = result.getByLabelText("Boiling point constant") as HTMLInputElement;
        kb.value = "0.512";
        fireEvent.input(kb);
        let kf = result.getByLabelText("Freezing point constant") as HTMLInputElement;
        kf.value = "1.86";
        fireEvent.input(kf);
        let bp = result.getByLabelText("Solvent boiling point") as HTMLInputElement;
        bp.value = "100";
        fireEvent.input(bp);
        let fp = result.getByLabelText("Solvent freezing point") as HTMLInputElement;
        fp.value = "0";
        fireEvent.input(fp);
        let p = result.getByLabelText("Solvent vapor pressure") as HTMLInputElement;
        p.value = "1";
        fireEvent.input(p);
        fireEvent.click(result.getByText("Calculate"));
        let text = await result.findByText(/Molality/);
        expect(text).toBeTruthy();
    });
    it("shows an error when solute mass is zero", async function (): Promise<void> {
        let result = render(function () { return <Colligative />; });
        let soluteMass = result.getByLabelText("Solute mass") as HTMLInputElement;
        soluteMass.value = "0";
        fireEvent.input(soluteMass);
        let molarMass = result.getByLabelText("Molar mass") as HTMLInputElement;
        molarMass.value = "58.5";
        fireEvent.input(molarMass);
        let solventMass = result.getByLabelText("Solvent mass") as HTMLInputElement;
        solventMass.value = "1000";
        fireEvent.input(solventMass);
        let vanthoff = result.getByLabelText("Van't Hoff factor") as HTMLInputElement;
        vanthoff.value = "1";
        fireEvent.input(vanthoff);
        fireEvent.click(result.getByText("Calculate"));
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
    });
    it("clears the result when the Clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <Colligative />; });
        let soluteMass = result.getByLabelText("Solute mass") as HTMLInputElement;
        soluteMass.value = "58.5";
        fireEvent.input(soluteMass);
        let molarMass = result.getByLabelText("Molar mass") as HTMLInputElement;
        molarMass.value = "58.5";
        fireEvent.input(molarMass);
        let solventMass = result.getByLabelText("Solvent mass") as HTMLInputElement;
        solventMass.value = "1000";
        fireEvent.input(solventMass);
        let vanthoff = result.getByLabelText("Van't Hoff factor") as HTMLInputElement;
        vanthoff.value = "1";
        fireEvent.input(vanthoff);
        let kb = result.getByLabelText("Boiling point constant") as HTMLInputElement;
        kb.value = "0.512";
        fireEvent.input(kb);
        let kf = result.getByLabelText("Freezing point constant") as HTMLInputElement;
        kf.value = "1.86";
        fireEvent.input(kf);
        let bp = result.getByLabelText("Solvent boiling point") as HTMLInputElement;
        bp.value = "100";
        fireEvent.input(bp);
        let fp = result.getByLabelText("Solvent freezing point") as HTMLInputElement;
        fp.value = "0";
        fireEvent.input(fp);
        let p = result.getByLabelText("Solvent vapor pressure") as HTMLInputElement;
        p.value = "1";
        fireEvent.input(p);
        fireEvent.click(result.getByText("Calculate"));
        let text = await result.findByText(/Molality/);
        expect(text).toBeTruthy();
        fireEvent.click(result.getByText("Clear"));
        expect(soluteMass.value).toBe("");
        expect(result.container.textContent).not.toMatch(/Molality/);
    });
});
