import {render, fireEvent, cleanup} from "@solidjs/testing-library";
import {describe, it, expect, afterEach} from "vitest";
import {Electrochemistry} from "./electrochemistry";
afterEach(function (): void {
    cleanup();
});
describe("Electrochemistry route", function (): void {
    it("renders the card with cell potential, nernst, and electrolysis sections", function (): void {
        let result = render(function () { return <Electrochemistry />; });
        let e1 = result.getByLabelText("First reduction potential") as HTMLInputElement;
        let e2 = result.getByLabelText("Second reduction potential") as HTMLInputElement;
        expect(e1).toBeTruthy();
        expect(e2).toBeTruthy();
        let standard = result.getByLabelText("Standard cell potential") as HTMLInputElement;
        let temperature = result.getByLabelText("Temperature") as HTMLInputElement;
        let electrons = result.getByLabelText("Number of electrons") as HTMLInputElement;
        let quotient = result.getByLabelText("Reaction quotient") as HTMLInputElement;
        expect(standard).toBeTruthy();
        expect(temperature).toBeTruthy();
        expect(electrons).toBeTruthy();
        expect(quotient).toBeTruthy();
        let mass = result.getByLabelText("Mass") as HTMLInputElement;
        let current = result.getByLabelText("Current") as HTMLInputElement;
        let time = result.getByLabelText("Time") as HTMLInputElement;
        let z = result.getByLabelText("Electrons per ion") as HTMLInputElement;
        let molarMass = result.getByLabelText("Molar mass") as HTMLInputElement;
        expect(mass).toBeTruthy();
        expect(current).toBeTruthy();
        expect(time).toBeTruthy();
        expect(z).toBeTruthy();
        expect(molarMass).toBeTruthy();
        let solveFor = result.getByLabelText("Select electrolysis parameter to solve for") as HTMLSelectElement;
        expect(solveFor).toBeTruthy();
        expect(solveFor.value).toBe("mass");
        expect(result.getByText("Calculate E°_cell")).toBeTruthy();
        expect(result.getByText("Calculate E")).toBeTruthy();
        expect(result.getByText("Calculate")).toBeTruthy();
        expect(result.getAllByText("Clear").length).toBe(3);
    });
    it("calculates cell potential E_cell = 1.100 V for E1=0.34 and E2=-0.76", async function (): Promise<void> {
        let result = render(function () { return <Electrochemistry />; });
        let e1 = result.getByLabelText("First reduction potential") as HTMLInputElement;
        e1.value = "0.34";
        fireEvent.input(e1);
        let e2 = result.getByLabelText("Second reduction potential") as HTMLInputElement;
        e2.value = "-0.76";
        fireEvent.input(e2);
        fireEvent.click(result.getByText("Calculate E°_cell"));
        let text = await result.findByText(/1\.100/);
        expect(text).toBeTruthy();
        expect(result.container.textContent).toMatch(/V/);
    });
    it("calculates nernst E approximately 1.159 V for E°=1.10, T=298, n=2, Q=0.01", async function (): Promise<void> {
        let result = render(function () { return <Electrochemistry />; });
        let standard = result.getByLabelText("Standard cell potential") as HTMLInputElement;
        standard.value = "1.10";
        fireEvent.input(standard);
        let temperature = result.getByLabelText("Temperature") as HTMLInputElement;
        temperature.value = "298";
        fireEvent.input(temperature);
        let electrons = result.getByLabelText("Number of electrons") as HTMLInputElement;
        electrons.value = "2";
        fireEvent.input(electrons);
        let quotient = result.getByLabelText("Reaction quotient") as HTMLInputElement;
        quotient.value = "0.01";
        fireEvent.input(quotient);
        fireEvent.click(result.getByText("Calculate E"));
        let text = await result.findByText(/E = E_standard/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/1\.159/);
    });
    it("calculates electrolysis mass approximately 63.510 g for I=1, t=96500, z=1, M=63.5", async function (): Promise<void> {
        let result = render(function () { return <Electrochemistry />; });
        let current = result.getByLabelText("Current") as HTMLInputElement;
        current.value = "1";
        fireEvent.input(current);
        let time = result.getByLabelText("Time") as HTMLInputElement;
        time.value = "96500";
        fireEvent.input(time);
        let z = result.getByLabelText("Electrons per ion") as HTMLInputElement;
        z.value = "1";
        fireEvent.input(z);
        let molarMass = result.getByLabelText("Molar mass") as HTMLInputElement;
        molarMass.value = "63.5";
        fireEvent.input(molarMass);
        fireEvent.click(result.getByText("Calculate"));
        let text = await result.findByText(/63\.510/);
        expect(text).toBeTruthy();
        expect(result.container.textContent).toMatch(/g/);
    });
    it("shows an error when cell potential inputs are missing", async function (): Promise<void> {
        let result = render(function () { return <Electrochemistry />; });
        let e1 = result.getByLabelText("First reduction potential") as HTMLInputElement;
        e1.value = "0.34";
        fireEvent.input(e1);
        fireEvent.click(result.getByText("Calculate E°_cell"));
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
    });
    it("shows an error when nernst Q is zero", async function (): Promise<void> {
        let result = render(function () { return <Electrochemistry />; });
        let standard = result.getByLabelText("Standard cell potential") as HTMLInputElement;
        standard.value = "1.10";
        fireEvent.input(standard);
        let temperature = result.getByLabelText("Temperature") as HTMLInputElement;
        temperature.value = "298";
        fireEvent.input(temperature);
        let electrons = result.getByLabelText("Number of electrons") as HTMLInputElement;
        electrons.value = "2";
        fireEvent.input(electrons);
        let quotient = result.getByLabelText("Reaction quotient") as HTMLInputElement;
        quotient.value = "0";
        fireEvent.input(quotient);
        fireEvent.click(result.getByText("Calculate E"));
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
    });
    it("clears the cell potential result when its Clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <Electrochemistry />; });
        let e1 = result.getByLabelText("First reduction potential") as HTMLInputElement;
        e1.value = "0.34";
        fireEvent.input(e1);
        let e2 = result.getByLabelText("Second reduction potential") as HTMLInputElement;
        e2.value = "-0.76";
        fireEvent.input(e2);
        fireEvent.click(result.getByText("Calculate E°_cell"));
        let text = await result.findByText(/1\.100/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[0]);
        expect(e1.value).toBe("");
        expect(result.container.textContent).not.toMatch(/1\.100/);
    });
    it("clears the electrolysis result when its Clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <Electrochemistry />; });
        let current = result.getByLabelText("Current") as HTMLInputElement;
        current.value = "1";
        fireEvent.input(current);
        let time = result.getByLabelText("Time") as HTMLInputElement;
        time.value = "96500";
        fireEvent.input(time);
        let z = result.getByLabelText("Electrons per ion") as HTMLInputElement;
        z.value = "1";
        fireEvent.input(z);
        let molarMass = result.getByLabelText("Molar mass") as HTMLInputElement;
        molarMass.value = "63.5";
        fireEvent.input(molarMass);
        fireEvent.click(result.getByText("Calculate"));
        let text = await result.findByText(/63\.510/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[2]);
        expect(current.value).toBe("");
        expect(result.container.textContent).not.toMatch(/63\.510/);
    });
});
