import {render, fireEvent, cleanup} from "@solidjs/testing-library";
import {describe, it, expect, afterEach} from "vitest";
import {GasLaws} from "./gas-laws";
afterEach(function (): void {
    cleanup();
});
describe("GasLaws route", function (): void {
    it("renders the card with ideal, combined, and vdw calculator sections", function (): void {
        let result = render(function () { return <GasLaws />; });
        let pressure = result.getByLabelText("Pressure") as HTMLInputElement;
        expect(pressure).toBeTruthy();
        let idealSolveFor = result.getByLabelText("Select ideal gas law parameter to solve for") as HTMLSelectElement;
        expect(idealSolveFor).toBeTruthy();
        expect(idealSolveFor.value).toBe("P");
        let rUnits = result.getByLabelText("Select gas constant units") as HTMLSelectElement;
        expect(rUnits).toBeTruthy();
        expect(rUnits.value).toBe("atm-L");
        let combinedSolveFor = result.getByLabelText("Select combined gas law parameter to solve for") as HTMLSelectElement;
        expect(combinedSolveFor).toBeTruthy();
        expect(combinedSolveFor.value).toBe("P1");
        let initialPressure = result.getByLabelText("Initial pressure") as HTMLInputElement;
        expect(initialPressure).toBeTruthy();
        let vdwA = result.getByLabelText("Van der Waals constant a") as HTMLInputElement;
        expect(vdwA).toBeTruthy();
        let vdwB = result.getByLabelText("Van der Waals constant b") as HTMLInputElement;
        expect(vdwB).toBeTruthy();
        expect(result.getAllByLabelText("Moles").length).toBe(2);
        expect(result.getAllByLabelText("Volume").length).toBe(2);
        expect(result.getAllByLabelText("Temperature").length).toBe(2);
        let calculateButtons = result.getAllByText("Calculate");
        expect(calculateButtons.length).toBe(2);
        expect(result.getByText("Calculate P")).toBeTruthy();
        expect(result.getAllByText("Clear").length).toBe(3);
    });
    it("solves ideal gas law for V given P=1, n=1, T=273.15, atm-L and displays approximately 22.4142 L", async function (): Promise<void> {
        let result = render(function () { return <GasLaws />; });
        let idealSolveFor = result.getByLabelText("Select ideal gas law parameter to solve for") as HTMLSelectElement;
        idealSolveFor.value = "V";
        fireEvent.change(idealSolveFor);
        let pressure = result.getByLabelText("Pressure") as HTMLInputElement;
        pressure.value = "1";
        fireEvent.input(pressure);
        let molesInputs = result.getAllByLabelText("Moles");
        let idealMoles = molesInputs[0] as HTMLInputElement;
        idealMoles.value = "1";
        fireEvent.input(idealMoles);
        let tempInputs = result.getAllByLabelText("Temperature");
        let idealTemp = tempInputs[0] as HTMLInputElement;
        idealTemp.value = "273.15";
        fireEvent.input(idealTemp);
        let calculateButtons = result.getAllByText("Calculate");
        fireEvent.click(calculateButtons[0]);
        let text = await result.findByText(/22\.414/);
        expect(text).toBeTruthy();
        expect(result.container.textContent).toMatch(/L/);
    });
    it("solves combined gas law for V2 given P1=1, V1=10, T1=300, P2=2, T2=400 and displays approximately 6.6667", async function (): Promise<void> {
        let result = render(function () { return <GasLaws />; });
        let combinedSolveFor = result.getByLabelText("Select combined gas law parameter to solve for") as HTMLSelectElement;
        combinedSolveFor.value = "V2";
        fireEvent.change(combinedSolveFor);
        let initialPressure = result.getByLabelText("Initial pressure") as HTMLInputElement;
        initialPressure.value = "1";
        fireEvent.input(initialPressure);
        let initialVolume = result.getByLabelText("Initial volume") as HTMLInputElement;
        initialVolume.value = "10";
        fireEvent.input(initialVolume);
        let initialTemp = result.getByLabelText("Initial temperature") as HTMLInputElement;
        initialTemp.value = "300";
        fireEvent.input(initialTemp);
        let finalPressure = result.getByLabelText("Final pressure") as HTMLInputElement;
        finalPressure.value = "2";
        fireEvent.input(finalPressure);
        let finalTemp = result.getByLabelText("Final temperature") as HTMLInputElement;
        finalTemp.value = "400";
        fireEvent.input(finalTemp);
        let calculateButtons = result.getAllByText("Calculate");
        fireEvent.click(calculateButtons[1]);
        let text = await result.findByText(/6\.6667/);
        expect(text).toBeTruthy();
    });
    it("solves van der waals for P given V=22.4, n=1, T=273, a=1.39, b=0.0391 and displays approximately 0.9991 atm", async function (): Promise<void> {
        let result = render(function () { return <GasLaws />; });
        let volumeInputs = result.getAllByLabelText("Volume");
        let vdwVolume = volumeInputs[volumeInputs.length - 1] as HTMLInputElement;
        vdwVolume.value = "22.4";
        fireEvent.input(vdwVolume);
        let molesInputs = result.getAllByLabelText("Moles");
        let vdwMoles = molesInputs[molesInputs.length - 1] as HTMLInputElement;
        vdwMoles.value = "1";
        fireEvent.input(vdwMoles);
        let tempInputs = result.getAllByLabelText("Temperature");
        let vdwTemp = tempInputs[tempInputs.length - 1] as HTMLInputElement;
        vdwTemp.value = "273";
        fireEvent.input(vdwTemp);
        let vdwA = result.getByLabelText("Van der Waals constant a") as HTMLInputElement;
        vdwA.value = "1.39";
        fireEvent.input(vdwA);
        let vdwB = result.getByLabelText("Van der Waals constant b") as HTMLInputElement;
        vdwB.value = "0.0391";
        fireEvent.input(vdwB);
        fireEvent.click(result.getByText("Calculate P"));
        let text = await result.findByText(/0\.9991/);
        expect(text).toBeTruthy();
        expect(result.container.textContent).toMatch(/atm/);
    });
    it("shows an error when ideal gas law is missing required inputs", async function (): Promise<void> {
        let result = render(function () { return <GasLaws />; });
        let molesInputs = result.getAllByLabelText("Moles");
        let idealMoles = molesInputs[0] as HTMLInputElement;
        idealMoles.value = "1";
        fireEvent.input(idealMoles);
        let tempInputs = result.getAllByLabelText("Temperature");
        let idealTemp = tempInputs[0] as HTMLInputElement;
        idealTemp.value = "273";
        fireEvent.input(idealTemp);
        let calculateButtons = result.getAllByText("Calculate");
        fireEvent.click(calculateButtons[0]);
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
    });
    it("clears the ideal gas law result when its Clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <GasLaws />; });
        let idealSolveFor = result.getByLabelText("Select ideal gas law parameter to solve for") as HTMLSelectElement;
        idealSolveFor.value = "V";
        fireEvent.change(idealSolveFor);
        let pressure = result.getByLabelText("Pressure") as HTMLInputElement;
        pressure.value = "1";
        fireEvent.input(pressure);
        let molesInputs = result.getAllByLabelText("Moles");
        let idealMoles = molesInputs[0] as HTMLInputElement;
        idealMoles.value = "1";
        fireEvent.input(idealMoles);
        let tempInputs = result.getAllByLabelText("Temperature");
        let idealTemp = tempInputs[0] as HTMLInputElement;
        idealTemp.value = "273.15";
        fireEvent.input(idealTemp);
        let calculateButtons = result.getAllByText("Calculate");
        fireEvent.click(calculateButtons[0]);
        let text = await result.findByText(/22\.414/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[0]);
        expect(pressure.value).toBe("");
        expect(result.container.textContent).not.toMatch(/22\.414/);
    });
    it("clears the combined gas law result when its Clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <GasLaws />; });
        let combinedSolveFor = result.getByLabelText("Select combined gas law parameter to solve for") as HTMLSelectElement;
        combinedSolveFor.value = "V2";
        fireEvent.change(combinedSolveFor);
        let initialPressure = result.getByLabelText("Initial pressure") as HTMLInputElement;
        initialPressure.value = "1";
        fireEvent.input(initialPressure);
        let initialVolume = result.getByLabelText("Initial volume") as HTMLInputElement;
        initialVolume.value = "10";
        fireEvent.input(initialVolume);
        let initialTemp = result.getByLabelText("Initial temperature") as HTMLInputElement;
        initialTemp.value = "300";
        fireEvent.input(initialTemp);
        let finalPressure = result.getByLabelText("Final pressure") as HTMLInputElement;
        finalPressure.value = "2";
        fireEvent.input(finalPressure);
        let finalTemp = result.getByLabelText("Final temperature") as HTMLInputElement;
        finalTemp.value = "400";
        fireEvent.input(finalTemp);
        let calculateButtons = result.getAllByText("Calculate");
        fireEvent.click(calculateButtons[1]);
        let text = await result.findByText(/6\.6667/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[1]);
        expect(initialPressure.value).toBe("");
        expect(result.container.textContent).not.toMatch(/6\.6667/);
    });
    it("clears the van der Waals result when its Clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <GasLaws />; });
        let volumeInputs = result.getAllByLabelText("Volume");
        let vdwVolume = volumeInputs[volumeInputs.length - 1] as HTMLInputElement;
        vdwVolume.value = "22.4";
        fireEvent.input(vdwVolume);
        let molesInputs = result.getAllByLabelText("Moles");
        let vdwMoles = molesInputs[molesInputs.length - 1] as HTMLInputElement;
        vdwMoles.value = "1";
        fireEvent.input(vdwMoles);
        let tempInputs = result.getAllByLabelText("Temperature");
        let vdwTemp = tempInputs[tempInputs.length - 1] as HTMLInputElement;
        vdwTemp.value = "273";
        fireEvent.input(vdwTemp);
        let vdwA = result.getByLabelText("Van der Waals constant a") as HTMLInputElement;
        vdwA.value = "1.39";
        fireEvent.input(vdwA);
        let vdwB = result.getByLabelText("Van der Waals constant b") as HTMLInputElement;
        vdwB.value = "0.0391";
        fireEvent.input(vdwB);
        fireEvent.click(result.getByText("Calculate P"));
        let text = await result.findByText(/0\.9991/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[clearButtons.length - 1]);
        expect(vdwA.value).toBe("");
        expect(result.container.textContent).not.toMatch(/0\.9991/);
    });
});
