import {render, fireEvent, cleanup} from "@solidjs/testing-library";
import {describe, it, expect, afterEach, beforeEach, vi} from "vitest";
import {ChartRenderer} from "../../modules/chartRenderer.js";
import {Kinetics} from "./kinetics";
afterEach(function (): void {
    cleanup();
});
describe("Kinetics route", function (): void {
    let renderLineChartSpy: ReturnType<typeof vi.spyOn>;
    let destroyChartSpy: ReturnType<typeof vi.spyOn>;
    beforeEach(function (): void {
        ChartRenderer.resetInstance();
        let instance = ChartRenderer.getInstance();
        renderLineChartSpy = vi.spyOn(Object.getPrototypeOf(instance), "renderLineChart").mockImplementation(function (): void { return; });
        destroyChartSpy = vi.spyOn(Object.getPrototypeOf(instance), "destroyChart").mockImplementation(function (): void { return; });
    });
    afterEach(function (): void {
        ChartRenderer.resetInstance();
        vi.restoreAllMocks();
    });
    it("renders the card with all five sub-calculator sections", function (): void {
        let result = render(function () { return <Kinetics />; });
        let arrheniusA = result.getByLabelText("Frequency factor") as HTMLInputElement;
        let arrheniusEa = result.getByLabelText("Arrhenius activation energy") as HTMLInputElement;
        let arrheniusT = result.getByLabelText("Arrhenius temperature") as HTMLInputElement;
        let arrheniusK = result.getByLabelText("Arrhenius rate constant") as HTMLInputElement;
        expect(arrheniusA).toBeTruthy();
        expect(arrheniusEa).toBeTruthy();
        expect(arrheniusT).toBeTruthy();
        expect(arrheniusK).toBeTruthy();
        let arrheniusSolveFor = result.getByLabelText("Select Arrhenius parameter to solve for") as HTMLSelectElement;
        expect(arrheniusSolveFor).toBeTruthy();
        expect(arrheniusSolveFor.value).toBe("k");
        let ratelawA1 = result.getByLabelText("Experiment 1 concentration A") as HTMLInputElement;
        let ratelawB1 = result.getByLabelText("Experiment 1 concentration B") as HTMLInputElement;
        let ratelawRate1 = result.getByLabelText("Experiment 1 rate") as HTMLInputElement;
        let ratelawA2 = result.getByLabelText("Experiment 2 concentration A") as HTMLInputElement;
        let ratelawB2 = result.getByLabelText("Experiment 2 concentration B") as HTMLInputElement;
        let ratelawRate2 = result.getByLabelText("Experiment 2 rate") as HTMLInputElement;
        expect(ratelawA1).toBeTruthy();
        expect(ratelawB1).toBeTruthy();
        expect(ratelawRate1).toBeTruthy();
        expect(ratelawA2).toBeTruthy();
        expect(ratelawB2).toBeTruthy();
        expect(ratelawRate2).toBeTruthy();
        let irlA0 = result.getByLabelText("Initial concentration") as HTMLInputElement;
        let irlK = result.getByLabelText("IRL rate constant") as HTMLInputElement;
        let irlT = result.getByLabelText("IRL time") as HTMLInputElement;
        let irlA = result.getByLabelText("Final concentration") as HTMLInputElement;
        expect(irlA0).toBeTruthy();
        expect(irlK).toBeTruthy();
        expect(irlT).toBeTruthy();
        expect(irlA).toBeTruthy();
        let irlSolveFor = result.getByLabelText("Select integrated rate law parameter to solve for") as HTMLSelectElement;
        expect(irlSolveFor.value).toBe("concentration");
        let irlOrder = result.getByLabelText("Select reaction order") as HTMLSelectElement;
        expect(irlOrder.value).toBe("1");
        let reactionOrderData = result.getByLabelText("Time-concentration data") as HTMLInputElement;
        expect(reactionOrderData).toBeTruthy();
        expect(reactionOrderData.type).toBe("text");
        let collisionEa = result.getByLabelText("Collision activation energy") as HTMLInputElement;
        let collisionT = result.getByLabelText("Collision temperature") as HTMLInputElement;
        let collisionZ = result.getByLabelText("Collision frequency") as HTMLInputElement;
        let collisionP = result.getByLabelText("Steric factor") as HTMLInputElement;
        let collisionK = result.getByLabelText("Collision rate constant") as HTMLInputElement;
        expect(collisionEa).toBeTruthy();
        expect(collisionT).toBeTruthy();
        expect(collisionZ).toBeTruthy();
        expect(collisionP).toBeTruthy();
        expect(collisionK).toBeTruthy();
        let collisionSolveFor = result.getByLabelText("Select collision theory parameter to solve for") as HTMLSelectElement;
        expect(collisionSolveFor.value).toBe("k");
        expect(result.getByText("Calculate Arrhenius")).toBeTruthy();
        expect(result.getByText("Determine Rate Law")).toBeTruthy();
        expect(result.getByText("Calculate IRL")).toBeTruthy();
        expect(result.getByText("Determine Order")).toBeTruthy();
        expect(result.getByText("Calculate Collision Theory")).toBeTruthy();
        expect(result.getAllByText("Clear").length).toBe(5);
    });
    it("calculates arrhenius k for A=1e13, Ea=75, T=298", async function (): Promise<void> {
        let result = render(function () { return <Kinetics />; });
        let arrheniusA = result.getByLabelText("Frequency factor") as HTMLInputElement;
        arrheniusA.value = "1e13";
        fireEvent.input(arrheniusA);
        let arrheniusEa = result.getByLabelText("Arrhenius activation energy") as HTMLInputElement;
        arrheniusEa.value = "75";
        fireEvent.input(arrheniusEa);
        let arrheniusT = result.getByLabelText("Arrhenius temperature") as HTMLInputElement;
        arrheniusT.value = "298";
        fireEvent.input(arrheniusT);
        fireEvent.click(result.getByText("Calculate Arrhenius"));
        let text = await result.findByText(/0\.7132/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/k = A/);
        expect(text.textContent).toMatch(/e\^\(/);
        expect(text.textContent).toMatch(/Ea\/RT/);
    });
    it("determines rate law for experiments with m=1 in A and n=0 in B", async function (): Promise<void> {
        let result = render(function () { return <Kinetics />; });
        let ratelawA1 = result.getByLabelText("Experiment 1 concentration A") as HTMLInputElement;
        ratelawA1.value = "0.1";
        fireEvent.input(ratelawA1);
        let ratelawB1 = result.getByLabelText("Experiment 1 concentration B") as HTMLInputElement;
        ratelawB1.value = "0.2";
        fireEvent.input(ratelawB1);
        let ratelawRate1 = result.getByLabelText("Experiment 1 rate") as HTMLInputElement;
        ratelawRate1.value = "0.004";
        fireEvent.input(ratelawRate1);
        let ratelawA2 = result.getByLabelText("Experiment 2 concentration A") as HTMLInputElement;
        ratelawA2.value = "0.2";
        fireEvent.input(ratelawA2);
        let ratelawB2 = result.getByLabelText("Experiment 2 concentration B") as HTMLInputElement;
        ratelawB2.value = "0.2";
        fireEvent.input(ratelawB2);
        let ratelawRate2 = result.getByLabelText("Experiment 2 rate") as HTMLInputElement;
        ratelawRate2.value = "0.008";
        fireEvent.input(ratelawRate2);
        fireEvent.click(result.getByText("Determine Rate Law"));
        let text = await result.findByText(/Order with respect to A/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/Order with respect to A: 1/);
        expect(text.textContent).toMatch(/Order with respect to B: 0/);
        expect(text.textContent).toMatch(/Rate constant k = 0\.0400/);
        expect(text.textContent).toMatch(/rate = 0\.0400\[A\]/);
    });
    it("calculates integrated rate law first order concentration and renders the chart", async function (): Promise<void> {
        let result = render(function () { return <Kinetics />; });
        let irlA0 = result.getByLabelText("Initial concentration") as HTMLInputElement;
        irlA0.value = "1";
        fireEvent.input(irlA0);
        let irlK = result.getByLabelText("IRL rate constant") as HTMLInputElement;
        irlK.value = "0.05";
        fireEvent.input(irlK);
        let irlT = result.getByLabelText("IRL time") as HTMLInputElement;
        irlT.value = "10";
        fireEvent.input(irlT);
        fireEvent.click(result.getByText("Calculate IRL"));
        let text = await result.findByText(/\[A\] = \[A\]/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/0\.6065/);
        expect(text.textContent).toMatch(/M/);
        expect(renderLineChartSpy).toHaveBeenCalled();
    });
    it("determines reaction order from exponential decay data as first order", async function (): Promise<void> {
        let result = render(function () { return <Kinetics />; });
        let reactionOrderData = result.getByLabelText("Time-concentration data") as HTMLInputElement;
        reactionOrderData.value = "0,1.0; 100,0.3679; 200,0.1353; 300,0.0498";
        fireEvent.input(reactionOrderData);
        fireEvent.click(result.getByText("Determine Order"));
        let text = await result.findByText(/Best-fit reaction order/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/Best-fit reaction order: 1/);
        expect(text.textContent).toMatch(/R/);
    });
    it("calculates collision theory k for Ea=50, T=298, Z=1e11, p=0.01", async function (): Promise<void> {
        let result = render(function () { return <Kinetics />; });
        let collisionEa = result.getByLabelText("Collision activation energy") as HTMLInputElement;
        collisionEa.value = "50";
        fireEvent.input(collisionEa);
        let collisionT = result.getByLabelText("Collision temperature") as HTMLInputElement;
        collisionT.value = "298";
        fireEvent.input(collisionT);
        let collisionZ = result.getByLabelText("Collision frequency") as HTMLInputElement;
        collisionZ.value = "1e11";
        fireEvent.input(collisionZ);
        let collisionP = result.getByLabelText("Steric factor") as HTMLInputElement;
        collisionP.value = "0.01";
        fireEvent.input(collisionP);
        fireEvent.click(result.getByText("Calculate Collision Theory"));
        let text = await result.findByText(/Fraction of effective collisions/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/k = Z/);
        expect(text.textContent).toMatch(/e\^\(/);
        expect(text.textContent).toMatch(/Ea\/RT/);
    });
    it("shows an error when arrhenius temperature is zero", async function (): Promise<void> {
        let result = render(function () { return <Kinetics />; });
        let arrheniusA = result.getByLabelText("Frequency factor") as HTMLInputElement;
        arrheniusA.value = "1e13";
        fireEvent.input(arrheniusA);
        let arrheniusEa = result.getByLabelText("Arrhenius activation energy") as HTMLInputElement;
        arrheniusEa.value = "75";
        fireEvent.input(arrheniusEa);
        let arrheniusT = result.getByLabelText("Arrhenius temperature") as HTMLInputElement;
        arrheniusT.value = "0";
        fireEvent.input(arrheniusT);
        fireEvent.click(result.getByText("Calculate Arrhenius"));
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
        expect(errorText.textContent).toMatch(/positive/);
        expect(renderLineChartSpy).not.toHaveBeenCalled();
    });
    it("clears the arrhenius result when its clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <Kinetics />; });
        let arrheniusA = result.getByLabelText("Frequency factor") as HTMLInputElement;
        arrheniusA.value = "1e13";
        fireEvent.input(arrheniusA);
        let arrheniusEa = result.getByLabelText("Arrhenius activation energy") as HTMLInputElement;
        arrheniusEa.value = "75";
        fireEvent.input(arrheniusEa);
        let arrheniusT = result.getByLabelText("Arrhenius temperature") as HTMLInputElement;
        arrheniusT.value = "298";
        fireEvent.input(arrheniusT);
        fireEvent.click(result.getByText("Calculate Arrhenius"));
        let text = await result.findByText(/0\.7132/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[0]);
        expect(arrheniusA.value).toBe("");
        expect(result.container.textContent).not.toMatch(/0\.7132/);
    });
});
