import {render, fireEvent, cleanup} from "@solidjs/testing-library";
import {describe, it, expect, afterEach} from "vitest";
import {QuantumAtomic} from "./quantum-atomic";
afterEach(function (): void {
    cleanup();
});
describe("QuantumAtomic route", function (): void {
    it("renders the card with all six sub-calculator sections", function (): void {
        let result = render(function () { return <QuantumAtomic />; });
        let principalQn = result.getByLabelText("Principal quantum number") as HTMLInputElement;
        let angularQn = result.getByLabelText("Angular momentum quantum number") as HTMLInputElement;
        let magneticQn = result.getByLabelText("Magnetic quantum number") as HTMLInputElement;
        let spinQn = result.getByLabelText("Spin quantum number") as HTMLInputElement;
        expect(principalQn).toBeTruthy();
        expect(angularQn).toBeTruthy();
        expect(magneticQn).toBeTruthy();
        expect(spinQn).toBeTruthy();
        let atomicNumber = result.getByLabelText("Atomic number for electron configuration") as HTMLInputElement;
        expect(atomicNumber).toBeTruthy();
        let rydbergN1 = result.getByLabelText("Rydberg lower energy level n1") as HTMLInputElement;
        let rydbergN2 = result.getByLabelText("Rydberg higher energy level n2") as HTMLInputElement;
        expect(rydbergN1).toBeTruthy();
        expect(rydbergN2).toBeTruthy();
        let deBroglieMass = result.getByLabelText("De Broglie mass") as HTMLInputElement;
        let deBroglieVelocity = result.getByLabelText("De Broglie velocity") as HTMLInputElement;
        expect(deBroglieMass).toBeTruthy();
        expect(deBroglieVelocity).toBeTruthy();
        let deBroglieMassUnit = result.getByLabelText("De Broglie mass unit") as HTMLSelectElement;
        expect(deBroglieMassUnit).toBeTruthy();
        expect(deBroglieMassUnit.value).toBe("kg");
        let peWavelength = result.getByLabelText("Photoelectric wavelength in nm") as HTMLInputElement;
        let peFrequency = result.getByLabelText("Photoelectric frequency in Hz") as HTMLInputElement;
        let peWorkFunction = result.getByLabelText("Photoelectric work function in eV") as HTMLInputElement;
        let peKe = result.getByLabelText("Photoelectric kinetic energy in eV") as HTMLInputElement;
        expect(peWavelength).toBeTruthy();
        expect(peFrequency).toBeTruthy();
        expect(peWorkFunction).toBeTruthy();
        expect(peKe).toBeTruthy();
        let peSolveFor = result.getByLabelText("Select photoelectric parameter to solve for") as HTMLSelectElement;
        expect(peSolveFor).toBeTruthy();
        expect(peSolveFor.value).toBe("KE");
        let heisDeltaX = result.getByLabelText("Uncertainty in position") as HTMLInputElement;
        let heisDeltaP = result.getByLabelText("Uncertainty in momentum") as HTMLInputElement;
        let heisMass = result.getByLabelText("Mass for delta-v calculation") as HTMLInputElement;
        expect(heisDeltaX).toBeTruthy();
        expect(heisDeltaP).toBeTruthy();
        expect(heisMass).toBeTruthy();
        let heisSolveFor = result.getByLabelText("Select Heisenberg parameter to solve for") as HTMLSelectElement;
        expect(heisSolveFor).toBeTruthy();
        expect(heisSolveFor.value).toBe("min-delta-x");
        expect(result.getByText("Validate Quantum Numbers")).toBeTruthy();
        expect(result.getByText("Generate Configuration")).toBeTruthy();
        expect(result.getByText("Calculate Rydberg")).toBeTruthy();
        expect(result.getByText("Calculate λ")).toBeTruthy();
        expect(result.getByText("Calculate Photoelectric")).toBeTruthy();
        expect(result.getByText("Calculate Heisenberg")).toBeTruthy();
        expect(result.getAllByText("Clear").length).toBe(6);
    });
    it("validates quantum numbers n=2, l=1, ml=0, ms=0.5 as a valid 2p orbital", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let principalQn = result.getByLabelText("Principal quantum number") as HTMLInputElement;
        principalQn.value = "2";
        fireEvent.input(principalQn);
        let angularQn = result.getByLabelText("Angular momentum quantum number") as HTMLInputElement;
        angularQn.value = "1";
        fireEvent.input(angularQn);
        let magneticQn = result.getByLabelText("Magnetic quantum number") as HTMLInputElement;
        magneticQn.value = "0";
        fireEvent.input(magneticQn);
        let spinQn = result.getByLabelText("Spin quantum number") as HTMLInputElement;
        spinQn.value = "0.5";
        fireEvent.input(spinQn);
        fireEvent.click(result.getByText("Validate Quantum Numbers"));
        let text = await result.findByText(/Orbital designation:/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/shell L/);
        expect(text.textContent).toMatch(/subshell p/);
        expect(text.textContent).toMatch(/Max electrons in 2p subshell: 6/);
    });
    it("generates electron configuration for Fe (Z=26) as [Ar] 3d6 4s2", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let atomicNumber = result.getByLabelText("Atomic number for electron configuration") as HTMLInputElement;
        atomicNumber.value = "26";
        fireEvent.input(atomicNumber);
        fireEvent.click(result.getByText("Generate Configuration"));
        let text = await result.findByText(/Full configuration:/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/1s2 2s2 2p6 3s2 3p6 4s2 3d6/);
        expect(text.textContent).toMatch(/Noble gas notation: \[Ar\] 4s2 3d6/);
        expect(text.textContent).toMatch(/Valence electrons: 8/);
    });
    it("calculates rydberg Balmer H-alpha line for n1=2, n2=3 at ~656 nm", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let rydbergN1 = result.getByLabelText("Rydberg lower energy level n1") as HTMLInputElement;
        rydbergN1.value = "2";
        fireEvent.input(rydbergN1);
        let rydbergN2 = result.getByLabelText("Rydberg higher energy level n2") as HTMLInputElement;
        rydbergN2.value = "3";
        fireEvent.input(rydbergN2);
        fireEvent.click(result.getByText("Calculate Rydberg"));
        let text = await result.findByText(/Spectral series:/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/Balmer/);
        expect(text.textContent).toMatch(/656\.34 nm/);
        expect(text.textContent).toMatch(/eV/);
    });
    it("calculates de Broglie wavelength for electron at 1e6 m/s as ~0.7274 nm", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let deBroglieMass = result.getByLabelText("De Broglie mass") as HTMLInputElement;
        deBroglieMass.value = "9.109e-31";
        fireEvent.input(deBroglieMass);
        let deBroglieVelocity = result.getByLabelText("De Broglie velocity") as HTMLInputElement;
        deBroglieVelocity.value = "1e6";
        fireEvent.input(deBroglieVelocity);
        fireEvent.click(result.getByText("Calculate λ"));
        let text = await result.findByText(/De Broglie wavelength:/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/0\.7274 nm/);
        expect(text.textContent).toMatch(/λ = h/);
    });
    it("calculates photoelectric KE for wavelength=400 nm and work function=2.3 eV", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let peWavelength = result.getByLabelText("Photoelectric wavelength in nm") as HTMLInputElement;
        peWavelength.value = "400";
        fireEvent.input(peWavelength);
        let peWorkFunction = result.getByLabelText("Photoelectric work function in eV") as HTMLInputElement;
        peWorkFunction.value = "2.3";
        fireEvent.input(peWorkFunction);
        fireEvent.click(result.getByText("Calculate Photoelectric"));
        let text = await result.findByText(/Photon energy:/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/Kinetic energy KE: 0\.80/);
        expect(text.textContent).toMatch(/Threshold wavelength:/);
    });
    it("calculates heisenberg minimum delta-x from delta-p=1e-24", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let heisDeltaP = result.getByLabelText("Uncertainty in momentum") as HTMLInputElement;
        heisDeltaP.value = "1e-24";
        fireEvent.input(heisDeltaP);
        fireEvent.click(result.getByText("Calculate Heisenberg"));
        let text = await result.findByText(/Minimum Δx:/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/Δx·Δp/);
        expect(text.textContent).toMatch(/J·s/);
    });
    it("shows an error when rydberg n2 is less than n1", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let rydbergN1 = result.getByLabelText("Rydberg lower energy level n1") as HTMLInputElement;
        rydbergN1.value = "3";
        fireEvent.input(rydbergN1);
        let rydbergN2 = result.getByLabelText("Rydberg higher energy level n2") as HTMLInputElement;
        rydbergN2.value = "2";
        fireEvent.input(rydbergN2);
        fireEvent.click(result.getByText("Calculate Rydberg"));
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
        expect(errorText.textContent).toMatch(/n2 must be greater than n1/);
    });
    it("clears the quantum numbers result when its clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let principalQn = result.getByLabelText("Principal quantum number") as HTMLInputElement;
        principalQn.value = "2";
        fireEvent.input(principalQn);
        let angularQn = result.getByLabelText("Angular momentum quantum number") as HTMLInputElement;
        angularQn.value = "1";
        fireEvent.input(angularQn);
        let magneticQn = result.getByLabelText("Magnetic quantum number") as HTMLInputElement;
        magneticQn.value = "0";
        fireEvent.input(magneticQn);
        let spinQn = result.getByLabelText("Spin quantum number") as HTMLInputElement;
        spinQn.value = "0.5";
        fireEvent.input(spinQn);
        fireEvent.click(result.getByText("Validate Quantum Numbers"));
        let text = await result.findByText(/Orbital designation:/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[0]);
        expect(principalQn.value).toBe("");
        expect(angularQn.value).toBe("");
        expect(result.container.textContent).not.toMatch(/Max electrons in 2p subshell/);
    });
    it("clears the electron configuration result when its clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let atomicNumber = result.getByLabelText("Atomic number for electron configuration") as HTMLInputElement;
        atomicNumber.value = "26";
        fireEvent.input(atomicNumber);
        fireEvent.click(result.getByText("Generate Configuration"));
        let text = await result.findByText(/Full configuration:/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[1]);
        expect(atomicNumber.value).toBe("");
        expect(result.container.textContent).not.toMatch(/Full configuration:/);
    });
    it("clears the rydberg result when its clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let rydbergN1 = result.getByLabelText("Rydberg lower energy level n1") as HTMLInputElement;
        rydbergN1.value = "2";
        fireEvent.input(rydbergN1);
        let rydbergN2 = result.getByLabelText("Rydberg higher energy level n2") as HTMLInputElement;
        rydbergN2.value = "3";
        fireEvent.input(rydbergN2);
        fireEvent.click(result.getByText("Calculate Rydberg"));
        let text = await result.findByText(/Spectral series:/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[2]);
        expect(rydbergN1.value).toBe("");
        expect(result.container.textContent).not.toMatch(/Spectral series:/);
    });
    it("clears the de Broglie result when its clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let deBroglieMass = result.getByLabelText("De Broglie mass") as HTMLInputElement;
        deBroglieMass.value = "9.109e-31";
        fireEvent.input(deBroglieMass);
        let deBroglieVelocity = result.getByLabelText("De Broglie velocity") as HTMLInputElement;
        deBroglieVelocity.value = "1e6";
        fireEvent.input(deBroglieVelocity);
        fireEvent.click(result.getByText("Calculate λ"));
        let text = await result.findByText(/De Broglie wavelength:/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[3]);
        expect(deBroglieMass.value).toBe("");
        expect(result.container.textContent).not.toMatch(/De Broglie wavelength:/);
    });
    it("clears the photoelectric result when its clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let peWavelength = result.getByLabelText("Photoelectric wavelength in nm") as HTMLInputElement;
        peWavelength.value = "400";
        fireEvent.input(peWavelength);
        let peWorkFunction = result.getByLabelText("Photoelectric work function in eV") as HTMLInputElement;
        peWorkFunction.value = "2.3";
        fireEvent.input(peWorkFunction);
        fireEvent.click(result.getByText("Calculate Photoelectric"));
        let text = await result.findByText(/Photon energy:/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[4]);
        expect(peWavelength.value).toBe("");
        expect(result.container.textContent).not.toMatch(/Photon energy:/);
    });
    it("clears the heisenberg result when its clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <QuantumAtomic />; });
        let heisDeltaP = result.getByLabelText("Uncertainty in momentum") as HTMLInputElement;
        heisDeltaP.value = "1e-24";
        fireEvent.input(heisDeltaP);
        fireEvent.click(result.getByText("Calculate Heisenberg"));
        let text = await result.findByText(/Minimum Δx:/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[5]);
        expect(heisDeltaP.value).toBe("");
        expect(result.container.textContent).not.toMatch(/Minimum Δx:/);
    });
});
