import {render, fireEvent, cleanup} from "@solidjs/testing-library";
import {describe, it, expect, afterEach} from "vitest";
import {SolutionMixing} from "./solution-mixing";
afterEach(function (): void {
    cleanup();
});
describe("SolutionMixing route", function (): void {
    it("renders the card with C1, V1, C2, V2 inputs and buttons", function (): void {
        let result = render(function () { return <SolutionMixing />; });
        let c1 = result.getByLabelText("Concentration 1") as HTMLInputElement;
        let v1 = result.getByLabelText("Volume 1") as HTMLInputElement;
        let c2 = result.getByLabelText("Concentration 2") as HTMLInputElement;
        let v2 = result.getByLabelText("Volume 2") as HTMLInputElement;
        expect(c1).toBeTruthy();
        expect(v1).toBeTruthy();
        expect(c2).toBeTruthy();
        expect(v2).toBeTruthy();
        expect(result.getByText("Calculate")).toBeTruthy();
        expect(result.getByText("Clear")).toBeTruthy();
    });
    it("calculates final concentration 0.7500 M for C1=1 V1=100 C2=0.5 V2=100", async function (): Promise<void> {
        let result = render(function () { return <SolutionMixing />; });
        let c1 = result.getByLabelText("Concentration 1") as HTMLInputElement;
        c1.value = "1";
        fireEvent.input(c1);
        let v1 = result.getByLabelText("Volume 1") as HTMLInputElement;
        v1.value = "100";
        fireEvent.input(v1);
        let c2 = result.getByLabelText("Concentration 2") as HTMLInputElement;
        c2.value = "0.5";
        fireEvent.input(c2);
        let v2 = result.getByLabelText("Volume 2") as HTMLInputElement;
        v2.value = "100";
        fireEvent.input(v2);
        fireEvent.click(result.getByText("Calculate"));
        let text = await result.findByText(/0\.7500/);
        expect(text).toBeTruthy();
        expect(result.container.textContent).toMatch(/M/);
    });
    it("shows an error when V1 is zero", async function (): Promise<void> {
        let result = render(function () { return <SolutionMixing />; });
        let c1 = result.getByLabelText("Concentration 1") as HTMLInputElement;
        c1.value = "1";
        fireEvent.input(c1);
        let v1 = result.getByLabelText("Volume 1") as HTMLInputElement;
        v1.value = "0";
        fireEvent.input(v1);
        let c2 = result.getByLabelText("Concentration 2") as HTMLInputElement;
        c2.value = "1";
        fireEvent.input(c2);
        let v2 = result.getByLabelText("Volume 2") as HTMLInputElement;
        v2.value = "100";
        fireEvent.input(v2);
        fireEvent.click(result.getByText("Calculate"));
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
    });
    it("clears the result when the Clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <SolutionMixing />; });
        let c1 = result.getByLabelText("Concentration 1") as HTMLInputElement;
        c1.value = "1";
        fireEvent.input(c1);
        let v1 = result.getByLabelText("Volume 1") as HTMLInputElement;
        v1.value = "100";
        fireEvent.input(v1);
        let c2 = result.getByLabelText("Concentration 2") as HTMLInputElement;
        c2.value = "0.5";
        fireEvent.input(c2);
        let v2 = result.getByLabelText("Volume 2") as HTMLInputElement;
        v2.value = "100";
        fireEvent.input(v2);
        fireEvent.click(result.getByText("Calculate"));
        let text = await result.findByText(/0\.7500/);
        expect(text).toBeTruthy();
        fireEvent.click(result.getByText("Clear"));
        expect(c1.value).toBe("");
        expect(result.container.textContent).not.toMatch(/0\.7500/);
    });
});
