import {render, fireEvent, cleanup} from "@solidjs/testing-library";
import {describe, it, expect, afterEach} from "vitest";
import {Thermodynamics} from "./thermodynamics";
afterEach(function (): void {
    cleanup();
});
describe("Thermodynamics route", function (): void {
    it("renders the card with all six calculator sections", function (): void {
        let result = render(function () { return <Thermodynamics />; });
        let enthalpyChange = result.getByLabelText("Enthalpy change") as HTMLInputElement;
        let entropyChange = result.getByLabelText("Entropy change") as HTMLInputElement;
        let temperature = result.getByLabelText("Temperature") as HTMLInputElement;
        expect(enthalpyChange).toBeTruthy();
        expect(entropyChange).toBeTruthy();
        expect(temperature).toBeTruthy();
        let enthalpySteps = result.getByLabelText("Enthalpy steps") as HTMLInputElement;
        expect(enthalpySteps).toBeTruthy();
        expect(enthalpySteps.type).toBe("text");
        let productEntropies = result.getByLabelText("Product entropies") as HTMLInputElement;
        let reactantEntropies = result.getByLabelText("Reactant entropies") as HTMLInputElement;
        expect(productEntropies).toBeTruthy();
        expect(reactantEntropies).toBeTruthy();
        expect(productEntropies.type).toBe("text");
        let heatCapSolveFor = result.getByLabelText("Select heat capacity parameter to solve for") as HTMLSelectElement;
        expect(heatCapSolveFor).toBeTruthy();
        expect(heatCapSolveFor.value).toBe("q");
        expect(result.getByLabelText("Mass")).toBeTruthy();
        expect(result.getByLabelText("Specific heat")).toBeTruthy();
        expect(result.getByLabelText("Initial temperature")).toBeTruthy();
        expect(result.getByLabelText("Final temperature")).toBeTruthy();
        expect(result.getByLabelText("Heat")).toBeTruthy();
        expect(result.getByLabelText("Enthalpy of formation")).toBeTruthy();
        expect(result.getByLabelText("Enthalpy of sublimation")).toBeTruthy();
        expect(result.getByLabelText("Ionization energy")).toBeTruthy();
        expect(result.getByLabelText("Enthalpy of dissociation")).toBeTruthy();
        expect(result.getByLabelText("Electron affinity")).toBeTruthy();
        expect(result.getByText("Calculate ΔG")).toBeTruthy();
        expect(result.getByText("Calculate Total ΔH")).toBeTruthy();
        expect(result.getByText("Calculate ΔS°")).toBeTruthy();
        expect(result.getByText("Calculate")).toBeTruthy();
        expect(result.getByText("Calculate ΔH")).toBeTruthy();
        expect(result.getByText("Calculate Lattice Energy")).toBeTruthy();
        expect(result.getAllByText("Clear").length).toBe(6);
        expect(result.getByText("Add broken bond")).toBeTruthy();
        expect(result.getByText("Add formed bond")).toBeTruthy();
        expect(result.getByText("No broken bonds added yet.")).toBeTruthy();
        expect(result.getByText("No formed bonds added yet.")).toBeTruthy();
    });
    it("calculates gibbs free energy for deltaH=-100, deltaS=200, T=298 as spontaneous", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        let enthalpyChange = result.getByLabelText("Enthalpy change") as HTMLInputElement;
        enthalpyChange.value = "-100";
        fireEvent.input(enthalpyChange);
        let entropyChange = result.getByLabelText("Entropy change") as HTMLInputElement;
        entropyChange.value = "200";
        fireEvent.input(entropyChange);
        let temperature = result.getByLabelText("Temperature") as HTMLInputElement;
        temperature.value = "298";
        fireEvent.input(temperature);
        fireEvent.click(result.getByText("Calculate ΔG"));
        let text = await result.findByText(/dG = dH/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/-159\.6000/);
        expect(result.container.textContent).toMatch(/Spontaneous/);
        expect(result.container.textContent).toMatch(/kJ\/mol/);
    });
    it("calculates hess law total deltaH for -100, 50, -200 as -250", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        let enthalpySteps = result.getByLabelText("Enthalpy steps") as HTMLInputElement;
        enthalpySteps.value = "-100, 50, -200";
        fireEvent.input(enthalpySteps);
        fireEvent.click(result.getByText("Calculate Total ΔH"));
        let text = await result.findByText(/-250\.0/);
        expect(text).toBeTruthy();
        expect(result.container.textContent).toMatch(/3 enthalpy steps/);
    });
    it("calculates entropy change for products 188.8 and reactants 130.7,205.2 as -147.1", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        let productEntropies = result.getByLabelText("Product entropies") as HTMLInputElement;
        productEntropies.value = "188.8";
        fireEvent.input(productEntropies);
        let reactantEntropies = result.getByLabelText("Reactant entropies") as HTMLInputElement;
        reactantEntropies.value = "130.7, 205.2";
        fireEvent.input(reactantEntropies);
        fireEvent.click(result.getByText("Calculate ΔS°"));
        let text = await result.findByText(/dS = S\(products\)/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/-147\.1000/);
        expect(result.container.textContent).toMatch(/J\/\(mol\*K\)/);
    });
    it("calculates heat capacity q for mass=100, c=4.184, initial=25, final=75 as 20920", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        let mass = result.getByLabelText("Mass") as HTMLInputElement;
        mass.value = "100";
        fireEvent.input(mass);
        let specificHeat = result.getByLabelText("Specific heat") as HTMLInputElement;
        specificHeat.value = "4.184";
        fireEvent.input(specificHeat);
        let initialTemp = result.getByLabelText("Initial temperature") as HTMLInputElement;
        initialTemp.value = "25";
        fireEvent.input(initialTemp);
        let finalTemp = result.getByLabelText("Final temperature") as HTMLInputElement;
        finalTemp.value = "75";
        fireEvent.input(finalTemp);
        fireEvent.click(result.getByText("Calculate"));
        let text = await result.findByText(/q = m\*c\*dT/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/20920\.0000/);
        expect(result.container.textContent).toMatch(/ J/);
    });
    it("calculates bond enthalpy via bond editor for O=O:1,H-H:2 broken and O-H:4 formed as -485 exothermic", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        fireEvent.click(result.getByText("Add broken bond"));
        let brokenTypes = result.getAllByLabelText("Bonds broken bond type");
        let firstBrokenSelect = brokenTypes[0] as HTMLSelectElement;
        firstBrokenSelect.value = "O=O";
        fireEvent.change(firstBrokenSelect);
        fireEvent.click(result.getByText("Add broken bond"));
        brokenTypes = result.getAllByLabelText("Bonds broken bond type");
        let secondBrokenSelect = brokenTypes[1] as HTMLSelectElement;
        secondBrokenSelect.value = "H-H";
        fireEvent.change(secondBrokenSelect);
        let brokenCounts = result.getAllByLabelText("Bonds broken count");
        let secondBrokenCount = brokenCounts[1] as HTMLInputElement;
        secondBrokenCount.value = "2";
        fireEvent.input(secondBrokenCount);
        fireEvent.click(result.getByText("Add formed bond"));
        let formedTypes = result.getAllByLabelText("Bonds formed bond type");
        let formedSelect = formedTypes[0] as HTMLSelectElement;
        formedSelect.value = "O-H";
        fireEvent.change(formedSelect);
        let formedCounts = result.getAllByLabelText("Bonds formed count");
        let formedCount = formedCounts[0] as HTMLInputElement;
        formedCount.value = "4";
        fireEvent.input(formedCount);
        fireEvent.click(result.getByText("Calculate ΔH"));
        let text = await result.findByText(/dH = bonds broken/);
        expect(text).toBeTruthy();
        expect(text.textContent).toMatch(/-485\.0000/);
        expect(result.container.textContent).toMatch(/Exothermic/);
    });
    it("calculates born-haber lattice energy for NaCl values as -788", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        let dHf = result.getByLabelText("Enthalpy of formation") as HTMLInputElement;
        dHf.value = "-411";
        fireEvent.input(dHf);
        let dHsub = result.getByLabelText("Enthalpy of sublimation") as HTMLInputElement;
        dHsub.value = "108";
        fireEvent.input(dHsub);
        let ie = result.getByLabelText("Ionization energy") as HTMLInputElement;
        ie.value = "496";
        fireEvent.input(ie);
        let dHdiss = result.getByLabelText("Enthalpy of dissociation") as HTMLInputElement;
        dHdiss.value = "244";
        fireEvent.input(dHdiss);
        let ea = result.getByLabelText("Electron affinity") as HTMLInputElement;
        ea.value = "-349";
        fireEvent.input(ea);
        fireEvent.click(result.getByText("Calculate Lattice Energy"));
        let text = await result.findByText(/-788/);
        expect(text).toBeTruthy();
        expect(result.container.textContent).toMatch(/kJ\/mol/);
    });
    it("shows an error when gibbs inputs are missing", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        let enthalpyChange = result.getByLabelText("Enthalpy change") as HTMLInputElement;
        enthalpyChange.value = "-100";
        fireEvent.input(enthalpyChange);
        fireEvent.click(result.getByText("Calculate ΔG"));
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
    });
    it("clears the gibbs result when its clear button is clicked", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        let enthalpyChange = result.getByLabelText("Enthalpy change") as HTMLInputElement;
        enthalpyChange.value = "-100";
        fireEvent.input(enthalpyChange);
        let entropyChange = result.getByLabelText("Entropy change") as HTMLInputElement;
        entropyChange.value = "200";
        fireEvent.input(entropyChange);
        let temperature = result.getByLabelText("Temperature") as HTMLInputElement;
        temperature.value = "298";
        fireEvent.input(temperature);
        fireEvent.click(result.getByText("Calculate ΔG"));
        let text = await result.findByText(/dG = dH/);
        expect(text).toBeTruthy();
        let clearButtons = result.getAllByText("Clear");
        fireEvent.click(clearButtons[0]);
        expect(enthalpyChange.value).toBe("");
        expect(result.container.textContent).not.toMatch(/dG = dH/);
    });
    it("bond editor shows an error when calculate is clicked with no bonds added", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        fireEvent.click(result.getByText("Calculate ΔH"));
        let errorText = await result.findByText(/Error/);
        expect(errorText).toBeTruthy();
        expect(result.container.textContent).toMatch(/both broken and formed/);
    });
    it("bond editor supports adding and removing broken bond rows", async function (): Promise<void> {
        let result = render(function () { return <Thermodynamics />; });
        expect(result.queryAllByLabelText("Bonds broken bond type").length).toBe(0);
        fireEvent.click(result.getByText("Add broken bond"));
        expect(result.getAllByLabelText("Bonds broken bond type").length).toBe(1);
        fireEvent.click(result.getByText("Add broken bond"));
        expect(result.getAllByLabelText("Bonds broken bond type").length).toBe(2);
        let removeButtons = result.getAllByLabelText("Remove broken bond");
        fireEvent.click(removeButtons[0]);
        expect(result.getAllByLabelText("Bonds broken bond type").length).toBe(1);
    });
});
