import type { ChemicalElement } from "../types";

export const mockElements: ChemicalElement[] = [
    {
        atomicNumber: 1,
        symbol: "H",
        name: "Hydrogen",
        atomicMass: 1.008,
        type: "non-metal",
        period: 1,
        group: 1,
        electronegativity: 2.20,
        electronAffinity: 72.8,
        atomicRadius: 53,
        ionizationEnergy: 1312,
        valenceElectrons: 1,
        totalElectrons: 1,
    },
    {
        atomicNumber: 6,
        symbol: "C",
        name: "Carbon",
        atomicMass: 12.011,
        type: "non-metal",
        period: 2,
        group: 14,
        electronegativity: 2.55,
        electronAffinity: 121.8,
        atomicRadius: 77,
        ionizationEnergy: 1086,
        valenceElectrons: 4,
        totalElectrons: 6,
    },
    {
        atomicNumber: 8,
        symbol: "O",
        name: "Oxygen",
        atomicMass: 15.999,
        type: "non-metal",
        period: 2,
        group: 16,
        electronegativity: 3.44,
        electronAffinity: 141.0,
        atomicRadius: 60,
        ionizationEnergy: 1314,
        valenceElectrons: 6,
        totalElectrons: 8,
    },
    {
        atomicNumber: 11,
        symbol: "Na",
        name: "Sodium",
        atomicMass: 22.990,
        type: "alkali metal",
        period: 3,
        group: 1,
        electronegativity: 0.93,
        electronAffinity: 52.9,
        atomicRadius: 186,
        ionizationEnergy: 496,
        valenceElectrons: 1,
        totalElectrons: 11,
    },
    {
        atomicNumber: 17,
        symbol: "Cl",
        name: "Chlorine",
        atomicMass: 35.45,
        type: "non-metal",
        period: 3,
        group: 17,
        electronegativity: 3.16,
        electronAffinity: 349.0,
        atomicRadius: 99,
        ionizationEnergy: 1251,
        valenceElectrons: 7,
        totalElectrons: 17,
    },
    {
        atomicNumber: 20,
        symbol: "Ca",
        name: "Calcium",
        atomicMass: 40.078,
        type: "alkaline earth metal",
        period: 4,
        group: 2,
        electronegativity: 1.00,
        electronAffinity: 2.4,
        atomicRadius: 197,
        ionizationEnergy: 590,
        valenceElectrons: 2,
        totalElectrons: 20,
    },
    {
        atomicNumber: 26,
        symbol: "Fe",
        name: "Iron",
        atomicMass: 55.845,
        type: "transition metal",
        period: 4,
        group: 8,
        electronegativity: 1.83,
        electronAffinity: 15.7,
        atomicRadius: 126,
        ionizationEnergy: 762,
        valenceElectrons: 2,
        totalElectrons: 26,
    },
    {
        atomicNumber: 29,
        symbol: "Cu",
        name: "Copper",
        atomicMass: 63.546,
        type: "transition metal",
        period: 4,
        group: 11,
        electronegativity: 1.90,
        electronAffinity: 118.4,
        atomicRadius: 128,
        ionizationEnergy: 745,
        valenceElectrons: 1,
        totalElectrons: 29,
    },
];

export function findElement(symbol: string): ChemicalElement | undefined {
    return mockElements.find(
        (el) => el.symbol.toLowerCase() === symbol.toLowerCase()
    );
}
