// Stub Wails bindings for TypeScript compilation
// These are auto-generated by `wails dev` or `wails build`
// This stub allows the project to compile without running Wails

export function GetPTableData(): Promise<string> {
    return Promise.reject(new Error("Wails bindings not available — run `wails dev` or `wails build` to generate"));
}
